language: ruby
notifications:
  email: false

rvm:
  - 2.2.5
  - 2.3.1
  - 2.5.3
  
matrix:
  include:
    - rvm: 2.1.2
      env: RAILS_VERSION=4.2.7.1

env:
  - "RAILS_VERSION=4.2.10"
  - "RAILS_VERSION=5.0.0.1"
