language: ruby
cache: bundler

rvm:
  - 2.5.3

env:
  - "RAILS_VERSION=4.2.11.1"
  - "RAILS_VERSION=5.2.3"
  - "RAILS_VERSION=6.0.0"

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: false
